version: 2

jobs:
  deploy:
    docker:
      - image: circleci/node:10.15.0

    steps:
      - checkout
      - run:
          name: Deploying to GitHub Pages
          command: |
            git config --global user.email "billie66@users.noreply.github.com"
            git config --global user.name "billie66"
            echo "machine github.com login billie66 password $GITHUB_TOKEN" > ~/.netrc
            cat ~/.netrc
            echo '# hello-circleci' > README.md
            git commit -a -m 'change readme' && git push

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
