version: 2

jobs:
  deploy:
    docker:
      - image: circleci/node:10.15.0

    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "8d:e0:26:c1:f2:cf:c4:19:59:bb:a2:bf:6c:23:ca:29"
      - run:
          name: Deploying to GitHub Pages
          command: |
            git config --global user.email "billie66@users.noreply.github.com"
            git config --global user.name "billie66"
            echo "machine github.com login billie66 password $GITHUB_TOKEN" > ~/.netrc
            cat ~/.netrc
            yarn install && GIT_USER=billie66 yarn build
            cd .. && git clone git@github.com:gatsbyci/gatsbyci.github.io.git gatsbyci
            cd gatsbyci && rm -rf * && git commit -a -m "remove readme" && git push

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
