version: 2

jobs:
  deploy:
    docker:
      - image: circleci/node:10.15.0

    steps:
      - checkout
      - run:
          name: Deploying to GitHub Pages
          command: |
            git config --global user.email "billie66@users.noreply.github.com"
            git config --global user.name "billie66"
            pwd

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
